exp:
    benchmark: 'autoencoder-mnist'
    name: 'VAE'
    seed: 1
    mode: 'default'
device: 'cuda:0'
trainer:
    algorithm: 'baseline'
    num_epochs: 100
data:
    datasets:
        - 'mnist'
        - 'fashionmnist'
        - 'kmnist'
    test_set: 'mnist'
    split_mode: 'train_val_test'
    channels: 1
    resize: 28
    cropsize: 28
    no_crop: True
    h_flips: False
    training:
        mode: 'self-supervised'
        task: 'reconstruction'
        batch_size: 64
    validation:
        mode: 'self-supervised'
        task: 'reconstruction'
        batch_size: 64
    test:
        mode: 'self-supervised'
        task: 'reconstruction'
        batch_size: 64
model:
    arch: 'mlp'
    hidden_dim: 1
    beta: 1
    new_weights: False
    optimizer: 'sgd'
    lr: 0.0001
    lr_gamma: 1
    momentum: 0.
    dampening: 0.
    nesterov: False
    wd: 0
    new_weights: False
    fixed: False
